[build]
  command = "npm run build"
  publish = "build/client" # This is the default for RRv7

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  included_files = ["build/server/**"]